version: '3'
services:
  app:
    container_name: sensor-simulator
    image: sensor-simulator:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8083:8083"

volumes:
  sensor-simulator:
