version: '3'
services:
  postgres:
    container_name: postgres-monitoring
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=monitoring-system
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - monitoring-system:/var/lib/postgresql/data
  app:
    container_name: monitoring-system
    image: monitoring-service:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/monitoring-system
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    links:
      - postgres

volumes:
  monitoring-system: