version: '3'
services:
  postgres:
    container_name: postgres-users
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=user-management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - user-management:/var/lib/postgresql/data
  app:
    container_name: user-management
    image: user-management-service:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-users:5432/user-management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    links:
      - postgres

volumes:
  user-management: