version: '3'
services:
  postgres:
    container_name: postgres-devices
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=device-management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - device-management:/var/lib/postgresql/data
  app:
    container_name: device-management
    image: device-management-service:latest
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/device-management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    links:
      - postgres

volumes:
  device-management:
